import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["src/index.ts"],
    format: ["esm", "cjs"],
    dts: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    treeshake: true,
    target: "node22",
    platform: "node",
    outDir: "dist",
    external: [
      "sqlite-vec",
      "node:sqlite",
      "node:fs",
      "node:path",
      "node:readline",
      "node:readline/promises",
      "pg",
      "pdf-parse",
      "mammoth",
      "tesseract.js",
    ],
  },
  {
    entry: { cli: "src/cli/index.ts" },
    format: ["esm"],
    dts: false,
    sourcemap: true,
    clean: false,
    splitting: false,
    treeshake: true,
    target: "node22",
    platform: "node",
    outDir: "dist",
    banner: {
      js: "#!/usr/bin/env node",
    },
    external: [
      "sqlite-vec",
      "node:sqlite",
      "node:fs",
      "node:path",
      "node:readline",
      "node:readline/promises",
    ],
  },
]);
